User.delete_all
User.create("username" => "UserA", "password" => "123456")
User.create("username" => "UserB", "password" => "123456")
User.create("username" => "UserC", "password" => "123456")
User.create("username" => "UserD", "password" => "123456")

City.delete_all
City.create("name" => "ORD", "x_axis" => "4198", "y_axis" => "-8790")
City.create("name" => "JFK", "x_axis" => "4065", "y_axis" => "-7378")
City.create("name" => "LGA", "x_axis" => "4078", "y_axis" => "-7387")
City.create("name" => "DTW", "x_axis" => "4222", "y_axis" => "-8336")
City.create("name" => "DFW", "x_axis" => "3290", "y_axis" => "-9704")
City.create("name" => "SFO", "x_axis" => "3762", "y_axis" => "-12238")

Airline.delete_all
Airline.create("iata" => "UA", "name" => "United Airline", "base" => "ORD")
Airline.create("iata" => "DL", "name" => "Delta Airline", "base" => "DTW")
Airline.create("iata" => "AA", "name" => "American Airline", "base" => "DAL")

Route.delete_all
Route.create("airline_id" => "3", "code" => "198", "depart_city_id" => "1", "arrival_city_id" => "2")
Route.create("airline_id" => "1", "code" => "1220", "depart_city_id" => "1", "arrival_city_id" => "3")
Route.create("airline_id" => "1", "code" => "668", "depart_city_id" => "1", "arrival_city_id" => "3")
Route.create("airline_id" => "1", "code" => "672", "depart_city_id" => "1", "arrival_city_id" => "3")
Route.create("airline_id" => "3", "code" => "398", "depart_city_id" => "1", "arrival_city_id" => "3")
Route.create("airline_id" => "3", "code" => "394", "depart_city_id" => "1", "arrival_city_id" => "3")
Route.create("airline_id" => "1", "code" => "3485", "depart_city_id" => "1", "arrival_city_id" => "5")
Route.create("airline_id" => "1", "code" => "1083", "depart_city_id" => "1", "arrival_city_id" => "5")
Route.create("airline_id" => "3", "code" => "2301", "depart_city_id" => "1", "arrival_city_id" => "5")
Route.create("airline_id" => "3", "code" => "2311", "depart_city_id" => "1", "arrival_city_id" => "5")
Route.create("airline_id" => "1", "code" => "715", "depart_city_id" => "1", "arrival_city_id" => "6")
Route.create("airline_id" => "1", "code" => "1141", "depart_city_id" => "1", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "2245", "depart_city_id" => "1", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "1399", "depart_city_id" => "1", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "119", "depart_city_id" => "2", "arrival_city_id" => "5")
Route.create("airline_id" => "3", "code" => "65", "depart_city_id" => "2", "arrival_city_id" => "5")
Route.create("airline_id" => "2", "code" => "2916", "depart_city_id" => "2", "arrival_city_id" => "5")
Route.create("airline_id" => "2", "code" => "2101", "depart_city_id" => "2", "arrival_city_id" => "4")
Route.create("airline_id" => "2", "code" => "2892", "depart_city_id" => "2", "arrival_city_id" => "4")
Route.create("airline_id" => "1", "code" => "821", "depart_city_id" => "2", "arrival_city_id" => "6")
Route.create("airline_id" => "2", "code" => "469", "depart_city_id" => "2", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "59", "depart_city_id" => "2", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "301", "depart_city_id" => "3", "arrival_city_id" => "1")
Route.create("airline_id" => "1", "code" => "635", "depart_city_id" => "3", "arrival_city_id" => "1")
Route.create("airline_id" => "2", "code" => "5931", "depart_city_id" => "3", "arrival_city_id" => "1")
Route.create("airline_id" => "3", "code" => "1103", "depart_city_id" => "3", "arrival_city_id" => "6")
Route.create("airline_id" => "2", "code" => "5997", "depart_city_id" => "3", "arrival_city_id" => "5")
Route.create("airline_id" => "3", "code" => "1107", "depart_city_id" => "3", "arrival_city_id" => "5")
Route.create("airline_id" => "1", "code" => "3475", "depart_city_id" => "4", "arrival_city_id" => "1")
Route.create("airline_id" => "2", "code" => "1399", "depart_city_id" => "4", "arrival_city_id" => "1")
Route.create("airline_id" => "2", "code" => "3476", "depart_city_id" => "4", "arrival_city_id" => "2")
Route.create("airline_id" => "2", "code" => "996", "depart_city_id" => "4", "arrival_city_id" => "2")
Route.create("airline_id" => "3", "code" => "1241", "depart_city_id" => "4", "arrival_city_id" => "5")
Route.create("airline_id" => "2", "code" => "3363", "depart_city_id" => "4", "arrival_city_id" => "5")
Route.create("airline_id" => "3", "code" => "2215", "depart_city_id" => "4", "arrival_city_id" => "5")
Route.create("airline_id" => "2", "code" => "1172", "depart_city_id" => "4", "arrival_city_id" => "6")
Route.create("airline_id" => "2", "code" => "2027", "depart_city_id" => "4", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "2328", "depart_city_id" => "5", "arrival_city_id" => "1")
Route.create("airline_id" => "1", "code" => "3514", "depart_city_id" => "5", "arrival_city_id" => "1")
Route.create("airline_id" => "1", "code" => "3474", "depart_city_id" => "5", "arrival_city_id" => "1")
Route.create("airline_id" => "2", "code" => "3324", "depart_city_id" => "5", "arrival_city_id" => "2")
Route.create("airline_id" => "3", "code" => "116", "depart_city_id" => "5", "arrival_city_id" => "2")
Route.create("airline_id" => "3", "code" => "1100", "depart_city_id" => "5", "arrival_city_id" => "3")
Route.create("airline_id" => "2", "code" => "5777", "depart_city_id" => "5", "arrival_city_id" => "3")
Route.create("airline_id" => "2", "code" => "1439", "depart_city_id" => "5", "arrival_city_id" => "4")
Route.create("airline_id" => "3", "code" => "43", "depart_city_id" => "5", "arrival_city_id" => "4")
Route.create("airline_id" => "1", "code" => "1042", "depart_city_id" => "5", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "1521", "depart_city_id" => "5", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "1677", "depart_city_id" => "5", "arrival_city_id" => "6")
Route.create("airline_id" => "3", "code" => "1494", "depart_city_id" => "6", "arrival_city_id" => "1")
Route.create("airline_id" => "1", "code" => "734", "depart_city_id" => "6", "arrival_city_id" => "1")
Route.create("airline_id" => "1", "code" => "688", "depart_city_id" => "6", "arrival_city_id" => "1")
Route.create("airline_id" => "2", "code" => "1859", "depart_city_id" => "6", "arrival_city_id" => "2")
Route.create("airline_id" => "3", "code" => "24", "depart_city_id" => "6", "arrival_city_id" => "2")
Route.create("airline_id" => "1", "code" => "808", "depart_city_id" => "6", "arrival_city_id" => "2")
Route.create("airline_id" => "2", "code" => "854", "depart_city_id" => "6", "arrival_city_id" => "4")
Route.create("airline_id" => "2", "code" => "1420", "depart_city_id" => "6", "arrival_city_id" => "4")
Route.create("airline_id" => "2", "code" => "1303", "depart_city_id" => "6", "arrival_city_id" => "4")
Route.create("airline_id" => "3", "code" => "1052", "depart_city_id" => "6", "arrival_city_id" => "5")
Route.create("airline_id" => "3", "code" => "1544", "depart_city_id" => "6", "arrival_city_id" => "5")
Route.create("airline_id" => "1", "code" => "452", "depart_city_id" => "6", "arrival_city_id" => "5")

Favorite.delete_all
Favorite.create("user_id" => "1", "route_id" => "8", "status" => "True")
Favorite.create("user_id" => "1", "route_id" => "13", "status" => "True")
Favorite.create("user_id" => "1", "route_id" => "22", "status" => "True")
Favorite.create("user_id" => "2", "route_id" => "23", "status" => "True")
Favorite.create("user_id" => "3", "route_id" => "35", "status" => "True")
Favorite.create("user_id" => "3", "route_id" => "22", "status" => "True")